# Generated by Django 4.2.8 on 2024-01-08 22:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+17804567892",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
