#!/bin/bash

set -o errexit

set -o nounset

worker_ready() {
    celery -A keppler inspect ping
}

until worker_ready; do 
    >&2 echo 'Celery workers are not ready...'
    sleep 1
done
>&2 echo 'Celery workers ready.'

flower \
    --app=keppler \
    --broker="${CELERY_BROKER}"