# Generated by Django 4.2.8 on 2024-01-08 22:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
    ]
