# Generated by Django 4.2.8 on 2024-03-27 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_product_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tax",
            field=models.DecimalField(
                decimal_places=2,
                default=0.05,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Tax",
            ),
        ),
    ]
