# Generated by Django 4.2.8 on 2024-04-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_category_subcategory_product_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="main_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="products.category",
                verbose_name="Main Category",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="products.subcategory",
                verbose_name="Parent Category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("name", "parent_category", "main_category")},
        ),
    ]
