# Generated by Django 4.2.8 on 2024-01-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about_me",
            field=models.TextField(
                default="What would you like others to know about you?",
                verbose_name="About me",
            ),
        ),
    ]
