# Generated by Django 4.2.8 on 2024-03-27 16:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_profile_about_me"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about_me",
            field=models.TextField(verbose_name="About me"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="00000000",
                max_length=30,
                region=None,
                verbose_name="phone Number",
            ),
        ),
    ]
