# Generated by Django 4.2.8 on 2024-04-08 17:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_profile_about_me_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about_me",
            field=models.TextField(
                default="Hello! I'm new here and currently working on filling out my profile. I have a wide range of products and skills that I'm excited to share with this community. Please check back later to learn more about me or feel free to reach out and connect!",
                verbose_name="About me",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+15555555555",
                max_length=30,
                region=None,
                verbose_name="phone Number",
            ),
        ),
    ]
