# Generated by Django 4.2.8 on 2024-04-09 01:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_profile_about_me_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+17809659789",
                max_length=30,
                region=None,
                verbose_name="phone Number",
            ),
        ),
    ]
